### ISSUE TITLE
About DWI datasets and some parameter representations

### ISSUE THREAD

**Issue by nana-zhang** [ins-amu/tvb-pipeline#2]
Hello, I'm trying to use this library to generate **connection matrix** and **SEEG gain matrix**, but I still have some questions.
 **1**.  Does DWI data only include DWI file?  and do I need**.bval** and  **.bvec** files? 
**2**. What data is needed to generate the gain matrix?I don't know what data **ELEC**, **ELEC_ENDPOINTS** and **ELEC_POS_GARDEL** represent.

**Comment by maedoc** [comment]
You can see some of the defaults [here](https://github.com/ins-amu/tvb-pipeline/blob/master/Makefile#L17). 

The DWI data can be a directory of DICOM files, or anything else that the MRtrix3 command `mrconvert` can handle.  I'd recommend doing this conversion to `.mif` format first. 

The `ELEC` variables specify an image with the contacts and alternatively the endpoints of the sEEG electrodes or the individual positions.  This is less well documented since each user may need to customize the code.

**Comment by nana-zhang** [comment]
Hello, thank you very much for your reply, so it is better to convert DWI data into **.mif** format, right? As for the electrode data, I already have the **positions** of each **contact**  of the **electrode**, so I can directly use it as input data, right?

Can you pay attention to my the other **issue**?
Thank you!

**Comment by maedoc** [comment]
I would convert to mif yes.  You can put the positions of contacts into a txt file which is read with the ELEC_POS_GARDEL option, though it's best to double check the relevant Python code to make sure it's being interpreted correctly.
